# This CI Workflow was deployed and configured by WarpWing ;)
name: SkyCrypt Image CI

on:
 push:
    branches: [ master ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag skycrypt:latest 
     
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: SkyCryptWebsite/SkyCrypt/skycrypt
        registry: docker.pkg.github.com
        username: ${{ secrets.ACTOR }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: Dockerfile
        tags: latest
      
